// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'candidate': string;
  'candidateId': string;
  'candidateName': string;
  'results': string;
  'searchButton': string;
  'searchRow': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
